// Word lists. Edit freely — just keep the shape:
// { word: "cat", sentence: "The cat sat on the mat.", emoji: "🐈" }
// Optional fields:
//   emoji      — picture shown above the word (leave off for abstract words)
//   homophone  — set to true for words that sound like another (e.g. there/their/they're).
//                The app will automatically play the sentence after saying the word.
//
// Levels and patterns follow the Australian Curriculum v9 (ACARA), NSW NESA
// English K–10 (2022) and Sound Waves scope and sequence. Australian English
// spellings are used throughout (colour, centre, mum, organise, travelled).
window.WORD_LISTS = {
  "Kindergarten": {
    "CVC words": [
      { word: "cat", sentence: "The cat sat on the mat.",         emoji: "🐈" },
      { word: "mat", sentence: "Wipe your feet on the mat." },
      { word: "hat", sentence: "She wore a red hat.",             emoji: "🎩" },
      { word: "ham", sentence: "I had ham on my sandwich." },
      { word: "bag", sentence: "Put it in your bag.",             emoji: "🎒" },
      { word: "bed", sentence: "I jumped on my bed.",             emoji: "🛏️" },
      { word: "leg", sentence: "I have a sore leg.",              emoji: "🦵" },
      { word: "ten", sentence: "I can count to ten.",             emoji: "🔟" },
      { word: "peg", sentence: "Hang the towel on the peg." },
      { word: "hen", sentence: "The hen laid an egg.",            emoji: "🐔" },
      { word: "pig", sentence: "The pig rolled in the mud.",      emoji: "🐷" },
      { word: "sit", sentence: "Sit on the chair, please." },
      { word: "fit", sentence: "These shoes fit me well." },
      { word: "lip", sentence: "I bit my lip." },
      { word: "six", sentence: "I am six years old." },
      { word: "dog", sentence: "My dog likes to run.",            emoji: "🐕" },
      { word: "log", sentence: "A frog sat on a log.",            emoji: "🪵" },
      { word: "top", sentence: "The book is on top.",             emoji: "⬆️" },
      { word: "hop", sentence: "Watch the bunny hop.",            emoji: "🐰" },
      { word: "mop", sentence: "Mum used a mop on the floor." },
      { word: "pot", sentence: "Soup boiled in the pot.",         emoji: "🍲" },
      { word: "mum", sentence: "My mum read me a story.",         emoji: "👩" },
      { word: "dad", sentence: "Dad made my lunch.",              emoji: "👨" },
      { word: "sun", sentence: "The sun is bright today.",        emoji: "☀️" },
      { word: "run", sentence: "We like to run fast.",            emoji: "🏃" },
      { word: "bug", sentence: "A tiny bug crawled past.",        emoji: "🐛" },
      { word: "nut", sentence: "The squirrel ate a nut.",         emoji: "🌰" },
      { word: "mud", sentence: "The pig played in the mud." },
      { word: "big", sentence: "That is a big truck.",            emoji: "🐘" },
      { word: "net", sentence: "We caught a fish in a net." }
    ],
    "Sight words": [
      { word: "the",  sentence: "The boy ran fast." },
      { word: "is",   sentence: "The sky is blue." },
      { word: "in",   sentence: "Put it in the box." },
      { word: "it",   sentence: "I can do it." },
      { word: "on",   sentence: "Sit on the chair." },
      { word: "am",   sentence: "I am five years old." },
      { word: "me",   sentence: "Come with me." },
      { word: "we",   sentence: "We are best friends." },
      { word: "see",  sentence: "I can see a bird.",              emoji: "👀", homophone: true },
      { word: "can",  sentence: "Can you help me?" },
      { word: "and",  sentence: "I like cats and dogs." },
      { word: "to",   sentence: "Let's go to the park." },
      { word: "said", sentence: "She said hello.",                emoji: "💬" },
      { word: "you",  sentence: "You are my best friend." },
      { word: "my",   sentence: "This is my book." },
      { word: "go",   sentence: "Let's go outside." },
      { word: "no",   sentence: "No, thank you." },
      { word: "up",   sentence: "Look up at the stars.",          emoji: "⬆️" },
      { word: "do",   sentence: "What do you want to do?" },
      { word: "for",  sentence: "This gift is for you.",          emoji: "🎁" },
      { word: "are",  sentence: "We are happy." },
      { word: "he",   sentence: "He is my brother." },
      { word: "she",  sentence: "She is my sister." }
    ],
    "Common nouns": [
      { word: "bus",  sentence: "The bus is yellow.",             emoji: "🚌" },
      { word: "fox",  sentence: "The fox has a bushy tail.",      emoji: "🦊" },
      { word: "cup",  sentence: "I drank from my cup.",           emoji: "☕" },
      { word: "jam",  sentence: "I like jam on toast.",           emoji: "🍓" },
      { word: "web",  sentence: "A spider made a web.",           emoji: "🕸️" },
      { word: "fan",  sentence: "The fan keeps me cool.",         emoji: "🌀" },
      { word: "jet",  sentence: "The jet flew over the clouds.",  emoji: "✈️" },
      { word: "ant",  sentence: "An ant crawled on my arm.",      emoji: "🐜" },
      { word: "bee",  sentence: "A bee buzzed past my ear.",      emoji: "🐝" },
      { word: "van",  sentence: "Dad drives a white van.",        emoji: "🚐" },
      { word: "doll", sentence: "I made a dress for my doll.",    emoji: "🪆" },
      { word: "jug",  sentence: "Fill the jug with water." },
      { word: "tap",  sentence: "Turn off the tap, please.",      emoji: "🚰" },
      { word: "pen",  sentence: "I wrote with a blue pen.",       emoji: "🖊️" },
      { word: "rat",  sentence: "The rat ran behind the box.",    emoji: "🐀" },
      { word: "cap",  sentence: "He wore a green cap.",           emoji: "🧢" }
    ]
  },

  "Year 1": {
    "Digraphs (sh, ch, th, ng, ck)": [
      { word: "ship", sentence: "The ship sailed away.",          emoji: "🚢" },
      { word: "shop", sentence: "We went to the shop." },
      { word: "fish", sentence: "A fish swims in the pond.",      emoji: "🐟" },
      { word: "dash", sentence: "Let's dash to the gate." },
      { word: "chop", sentence: "I helped chop the carrots.",     emoji: "🥕" },
      { word: "chip", sentence: "Have a chip from my plate.",     emoji: "🍟" },
      { word: "much", sentence: "Thank you very much." },
      { word: "rich", sentence: "The king was very rich." },
      { word: "then", sentence: "I'll see you then." },
      { word: "thin", sentence: "The ice was very thin." },
      { word: "bath", sentence: "Time to get in the bath.",       emoji: "🛁" },
      { word: "with", sentence: "Come with me to the park." },
      { word: "when", sentence: "When can we eat?" },
      { word: "what", sentence: "What is your name?",             emoji: "❓" },
      { word: "sing", sentence: "Birds sing in the morning.",     emoji: "🎵" },
      { word: "ring", sentence: "She wore a gold ring.",          emoji: "💍" },
      { word: "long", sentence: "The snake was very long.",       emoji: "🐍" },
      { word: "duck", sentence: "The duck splashed in the pond.", emoji: "🦆" },
      { word: "sock", sentence: "I lost one sock.",               emoji: "🧦" },
      { word: "kick", sentence: "He gave the ball a kick.",       emoji: "⚽" }
    ],
    "Magic-e words": [
      { word: "make", sentence: "Let's make a sandcastle.",       emoji: "🏖️" },
      { word: "name", sentence: "Write your name at the top." },
      { word: "gate", sentence: "Open the gate, please." },
      { word: "save", sentence: "Save your drawing for me." },
      { word: "ride", sentence: "I love to ride my bike.",        emoji: "🚲" },
      { word: "kite", sentence: "Fly your kite in the wind.",     emoji: "🪁" },
      { word: "time", sentence: "What time is it?",               emoji: "⏰" },
      { word: "line", sentence: "Stand in a line, please." },
      { word: "side", sentence: "Sit on the other side." },
      { word: "home", sentence: "We went home for dinner.",       emoji: "🏠" },
      { word: "hope", sentence: "I hope it doesn't rain." },
      { word: "bone", sentence: "The dog buried his bone.",       emoji: "🦴" },
      { word: "nose", sentence: "Wipe your nose, please.",        emoji: "👃" },
      { word: "rose", sentence: "Mum picked a red rose.",         emoji: "🌹" },
      { word: "cute", sentence: "The puppy is so cute.",          emoji: "🐶" },
      { word: "tube", sentence: "Toothpaste comes in a tube." },
      { word: "mule", sentence: "The mule carried the load.",     emoji: "🫏" },
      { word: "late", sentence: "Don't be late for school." }
    ],
    "Consonant blends": [
      { word: "stop",  sentence: "Stop at the red light.",        emoji: "🛑" },
      { word: "spin",  sentence: "Watch the top spin around." },
      { word: "snap",  sentence: "Snap the lid on tightly." },
      { word: "swim",  sentence: "Fish swim in the sea.",         emoji: "🏊" },
      { word: "plan",  sentence: "We made a plan together." },
      { word: "plant", sentence: "Plant the seed in the soil.",   emoji: "🌱" },
      { word: "clap",  sentence: "Clap your hands to the music.", emoji: "👏" },
      { word: "glad",  sentence: "I'm glad to see you." },
      { word: "frog",  sentence: "A green frog hopped past.",     emoji: "🐸" },
      { word: "grin",  sentence: "He gave me a big grin.",        emoji: "😀" },
      { word: "drum",  sentence: "He played the drum loudly.",    emoji: "🥁" },
      { word: "trip",  sentence: "Our trip starts tomorrow.",     emoji: "🧳" },
      { word: "jump",  sentence: "Frogs love to jump.",           emoji: "🐸" },
      { word: "hand",  sentence: "Hold my hand.",                 emoji: "✋" },
      { word: "sand",  sentence: "We built castles in the sand.", emoji: "🏖️" },
      { word: "milk",  sentence: "I drink milk every day.",       emoji: "🥛" },
      { word: "lamp",  sentence: "Turn on the lamp, please.",     emoji: "💡" },
      { word: "nest",  sentence: "Birds built a nest in the tree.", emoji: "🪺" },
      { word: "flag",  sentence: "The flag flew high.",           emoji: "🚩" }
    ]
  },

  "Year 2": {
    /*
    "Vowel teams (long vowels)": [
      { word: "rain",   sentence: "The rain made puddles.",       emoji: "🌧️" },
      { word: "train",  sentence: "We took the train to the city.", emoji: "🚂" },
      { word: "paint",  sentence: "Mum painted the wall blue.",   emoji: "🎨" },
      { word: "boat",   sentence: "Our boat sailed on the lake.", emoji: "⛵" },
      { word: "road",   sentence: "The road was long and straight.", emoji: "🛣️" },
      { word: "coast",  sentence: "We drove along the coast." },
      { word: "light",  sentence: "Turn off the light, please.",  emoji: "💡" },
      { word: "bright", sentence: "The stars are very bright.",   emoji: "⭐" },
      { word: "way",    sentence: "Show me the way home." },
      { word: "play",   sentence: "We can play in the garden.",   emoji: "🎮" },
      { word: "today",  sentence: "Today is my birthday.",        emoji: "🎂" },
      { word: "slow",   sentence: "Walk slow on the ice.",        emoji: "🐢" },
      { word: "snow",   sentence: "Snow covered the hills.",      emoji: "❄️" },
      { word: "grow",   sentence: "Sunflowers grow very tall.",   emoji: "🌻" },
      { word: "sleep",  sentence: "I need a good sleep.",         emoji: "😴" },
      { word: "tree",   sentence: "The bird sat in a tree.",      emoji: "🌳" },
      { word: "moon",   sentence: "The moon is full tonight.",    emoji: "🌕" },
      { word: "food",   sentence: "I love spicy food.",           emoji: "🍜" }
    ],
    "R-controlled & diphthongs": [
      { word: "park",  sentence: "We rode bikes in the park.",    emoji: "🏞️" },
      { word: "dark",  sentence: "It was very dark in the cave.", emoji: "🌑" },
      { word: "fork",  sentence: "Use a fork to eat.",            emoji: "🍴" },
      { word: "sport", sentence: "Cricket is my favourite sport.", emoji: "🏏" },
      { word: "bird",  sentence: "A bird flew past my window.",   emoji: "🐦" },
      { word: "first", sentence: "I came first in the race.",     emoji: "🥇" },
      { word: "girl",  sentence: "The girl waved hello.",         emoji: "👧" },
      { word: "chair", sentence: "Sit on the chair.",             emoji: "🪑" },
      { word: "stair", sentence: "Climb the stair carefully." },
      { word: "near",  sentence: "The shop is near the school." },
      { word: "boy",   sentence: "The boy kicked the ball.",      emoji: "👦" },
      { word: "joy",   sentence: "Her face was full of joy.",     emoji: "😊" },
      { word: "soil",  sentence: "Plants grow in the soil.",      emoji: "🌱" },
      { word: "point", sentence: "Don't point at people." },
      { word: "cloud", sentence: "A grey cloud crossed the sky.", emoji: "☁️" },
      { word: "down",  sentence: "Climb down the ladder.",        emoji: "⬇️" },
      { word: "town",  sentence: "Our town has a lake.",          emoji: "🏘️" },
      { word: "brown", sentence: "She has brown hair.",           emoji: "🟫" }
    ],
    "Silent letters & tricky patterns": [
      { word: "knee",    sentence: "I scraped my knee on the path." },
      { word: "know",    sentence: "I know the answer." },
      { word: "knife",   sentence: "The knife is very sharp.",    emoji: "🔪" },
      { word: "write",   sentence: "Write your name at the top.", emoji: "✍️" },
      { word: "wrap",    sentence: "Help me wrap the present.",   emoji: "🎁", homophone:true },
      { word: "lamb",    sentence: "A baby sheep is called a lamb.", emoji: "🐑" },
      { word: "thumb",   sentence: "I sucked my thumb when I was little.", emoji: "👍" },
      { word: "match",   sentence: "These shoes are a match.",    emoji: "👟" },
      { word: "catch",   sentence: "Catch the ball!",             emoji: "🏐" },
      { word: "bridge",  sentence: "We crossed the bridge.",      emoji: "🌉" },
      { word: "edge",    sentence: "Stand back from the edge." },
      { word: "hopping", sentence: "The bunny was hopping along.", emoji: "🐰" },
      { word: "baking",  sentence: "Grandma is baking biscuits.", emoji: "🍪" },
      { word: "crying",  sentence: "The baby was crying loudly.", emoji: "😢" },
      { word: "city",    sentence: "We visited the big city.",    emoji: "🏙️" },
      { word: "cage",    sentence: "The parrot is in its cage.",  emoji: "🦜" },
      { word: "race",    sentence: "I won the running race.",     emoji: "🏃" },
      { word: "fence",   sentence: "The dog jumped the fence." }
    ],
    */
    "Common words (set 1)": [
      { word: "said",     sentence: "She said hello to her friend.",       emoji: "💬" },
      { word: "they",     sentence: "They went to the park." },
      { word: "when",     sentence: "When can we go outside?" },
      { word: "how",      sentence: "How do you tie your shoes?" },
      { word: "here",     sentence: "Come over here, please.",             homophone: true },
      { word: "there",    sentence: "Put it over there.",                  homophone: true },
      { word: "were",     sentence: "They were playing outside." },
      { word: "two",      sentence: "I have two hands.",                   homophone: true },
      { word: "each",     sentence: "Each child got a turn." },
      { word: "after",    sentence: "We play after school." },
      { word: "first",    sentence: "I came first in the race.",           emoji: "🥇" },
      { word: "use",      sentence: "Use your pencil to write.",           emoji: "✏️" },
      { word: "our",      sentence: "This is our classroom." },
      { word: "too",      sentence: "I want to come too.",                 homophone: true },
      { word: "keep",     sentence: "Keep your room tidy." },
      { word: "put",      sentence: "Put your bag away.",                  emoji: "🎒" },
      { word: "now",      sentence: "We need to go now." },
      { word: "does",     sentence: "Does your dog do tricks?" },
      { word: "about",    sentence: "Tell me about your day." }
    ],
    "Common words (set 2)": [
      { word: "done",     sentence: "I am done with my work." },
      { word: "house",    sentence: "We live in a big house.",             emoji: "🏠" },
      { word: "know",     sentence: "I know the answer.",                  homophone: true },
      { word: "walk",     sentence: "Let's walk to school.",               emoji: "🚶" },
      { word: "want",     sentence: "I want a glass of water." },
      { word: "full",     sentence: "My cup is full." },
      { word: "friend",   sentence: "She is my best friend.",              emoji: "👫" },
      { word: "family",   sentence: "My family loves camping.",            emoji: "👨‍👩‍👧‍👦" },
      { word: "many",     sentence: "There are many stars in the sky.",    emoji: "⭐" },
      { word: "better",   sentence: "I feel much better today." },
      { word: "could",    sentence: "Could you help me, please?" },
      { word: "brother",  sentence: "My brother is older than me." },
      { word: "four",     sentence: "A dog has four legs.",                homophone: true },
      { word: "who",      sentence: "Who is at the door?" },
      { word: "buy",      sentence: "Let's buy some apples.",              homophone: true },
      { word: "their",    sentence: "Their dog is very friendly.",         homophone: true },
      { word: "would",    sentence: "Would you like some cake?",           emoji: "🎂" },
      { word: "won",      sentence: "Our team won the game.",              emoji: "🏆", homophone: true },
      { word: "always",   sentence: "I always brush my teeth." },
      { word: "people",   sentence: "Many people came to the show.",       emoji: "👥" }
    ],
    "Common words (set 3)": [
      { word: "night",     sentence: "Stars shine at night.",              emoji: "🌙", homophone: true },
      { word: "write",     sentence: "Write your name on the line.",      emoji: "✍️", homophone: true },
      { word: "again",     sentence: "Let's try again." },
      { word: "every",     sentence: "Every child got a prize." },
      { word: "really",    sentence: "I really like ice cream.",           emoji: "🍦" },
      { word: "where",     sentence: "Where are my shoes?",               homophone: true },
      { word: "inside",    sentence: "Come inside before it rains." },
      { word: "hurt",      sentence: "I hurt my knee." },
      { word: "other",     sentence: "Give me the other one." },
      { word: "found",     sentence: "I found a shell on the beach.",     emoji: "🐚" },
      { word: "around",    sentence: "We walked around the park." },
      { word: "round",     sentence: "The ball is round.",                emoji: "⚽" },
      { word: "before",    sentence: "Wash your hands before dinner." },
      { word: "should",    sentence: "You should eat your vegetables." },
      { word: "own",       sentence: "I have my own room." },
      { word: "under",     sentence: "The cat hid under the bed.",        emoji: "🐱" },
      { word: "which",     sentence: "Which book do you want?" },
      { word: "eight",     sentence: "I am eight years old.",             homophone: true },
      { word: "birthday",  sentence: "Today is my birthday.",             emoji: "🎂" },
      { word: "please",    sentence: "Can I have some, please?" },
      { word: "these",     sentence: "These are my favourite shoes." },
      { word: "those",     sentence: "Look at those birds!",              emoji: "🐦" },
      { word: "yesterday", sentence: "Yesterday we went to the zoo.",     emoji: "🦁" }
    ]
  },

  "Year 3": {
    "Prefixes & suffixes": [
      { word: "unkind",    sentence: "It's unkind to tease others." },
      { word: "unhappy",   sentence: "He felt unhappy after the loss." },
      { word: "undo",      sentence: "I had to undo my shoelace." },
      { word: "replay",    sentence: "Let's replay the goal.",    emoji: "🔁" },
      { word: "return",    sentence: "I need to return my library book.", emoji: "📚" },
      { word: "disagree",  sentence: "I disagree with that idea." },
      { word: "dislike",   sentence: "I dislike olives." },
      { word: "mistake",   sentence: "Everyone makes a mistake sometimes." },
      { word: "preview",   sentence: "We watched a preview of the movie.", emoji: "🎬" },
      { word: "careful",   sentence: "Be careful crossing the road." },
      { word: "useful",    sentence: "A torch is useful at night." },
      { word: "hopeless",  sentence: "The wet match was hopeless." },
      { word: "useless",   sentence: "This pen is useless without ink." },
      { word: "slowly",    sentence: "Walk slowly down the hill.", emoji: "🐢" },
      { word: "quickly",   sentence: "She quickly tied her shoes." },
      { word: "kindness",  sentence: "Her kindness made me smile.", emoji: "💖" },
      { word: "sadness",   sentence: "I felt sadness when my pet died." },
      { word: "payment",   sentence: "We sent the payment yesterday.", emoji: "💰" },
      { word: "agreement", sentence: "We came to an agreement." },
      { word: "taller",    sentence: "My brother is taller than me." },
      { word: "smallest",  sentence: "I picked the smallest apple.", emoji: "🍎" },
      { word: "happiest",  sentence: "This is the happiest day.",  emoji: "😄" }
    ],
    "Common words": [
      { word: "because", sentence: "I'm sleepy because it's late." },
      { word: "friend",  sentence: "She is my best friend.",      emoji: "👫" },
      { word: "before",  sentence: "Brush your teeth before bed." },
      { word: "again",   sentence: "Let's try again." },
      { word: "after",   sentence: "We play after school." },
      { word: "often",   sentence: "We often go to the beach." },
      { word: "journey", sentence: "Our journey took two days." },
      { word: "hurry",   sentence: "Hurry or we'll miss the bus.", emoji: "🏃" },
      { word: "board",   sentence: "Write it on the board." },
      { word: "cheer",   sentence: "We cheer for our team.",      emoji: "📣" },
      { word: "around",  sentence: "We walked around the lake." },
      { word: "every",   sentence: "Every kid got a turn." },
      { word: "another", sentence: "Can I have another biscuit?" },
      { word: "family",  sentence: "My family went to the beach.", emoji: "👨‍👩‍👧‍👦" },
      { word: "mother",  sentence: "My mother bakes lovely bread." },
      { word: "father",  sentence: "My father reads the news every day." },
      { word: "brother", sentence: "My brother plays football.",  emoji: "⚽" },
      { word: "water",   sentence: "Drink lots of water in summer.", emoji: "💧" },
      { word: "school",  sentence: "I walk to school each day.",  emoji: "🏫" },
      { word: "would",   sentence: "I would like a cold drink." },
      { word: "could",   sentence: "Could you pass the salt?" },
      { word: "people",  sentence: "Lots of people came to the show.", emoji: "👥" }
    ],
    "Homophones": [
      { word: "their",   sentence: "Their car is blue.",                                homophone: true },
      { word: "there",   sentence: "Put it over there.",                                homophone: true },
      { word: "they're", sentence: "They're coming to my party.",                       homophone: true },
      { word: "hear",    sentence: "Did you hear that noise?",            emoji: "👂",  homophone: true },
      { word: "here",    sentence: "Come over here, please.",                           homophone: true },
      { word: "bear",    sentence: "A brown bear lives in the cave.",     emoji: "🐻",  homophone: true },
      { word: "bare",    sentence: "His feet were bare on the sand.",     emoji: "🦶",  homophone: true },
      { word: "pair",    sentence: "I bought a new pair of shoes.",       emoji: "👟",  homophone: true },
      { word: "pear",    sentence: "She ate a juicy green pear.",         emoji: "🍐",  homophone: true },
      { word: "knight",  sentence: "The knight rode a strong horse.",     emoji: "🐴",  homophone: true },
      { word: "night",   sentence: "Stars shine in the night sky.",       emoji: "🌙",  homophone: true },
      { word: "won",     sentence: "Our team won the game.",              emoji: "🏆",  homophone: true },
      { word: "one",     sentence: "I have one apple left.",                            homophone: true },
      { word: "sea",     sentence: "We swam in the warm sea.",            emoji: "🌊",  homophone: true },
      { word: "blue",    sentence: "The sky is bright blue today.",       emoji: "🔵",  homophone: true },
      { word: "blew",    sentence: "The wind blew my hat away.",                        homophone: true },
      { word: "sun",     sentence: "The sun warmed my face.",             emoji: "☀️",  homophone: true },
      { word: "son",     sentence: "She is proud of her son.",                          homophone: true },
      { word: "too",     sentence: "I want some ice cream too.",                        homophone: true },
      { word: "two",     sentence: "I have two pencils.",                               homophone: true }
    ]
  },

  "Year 4": {
    "Plural rules": [
      { word: "babies",   sentence: "The babies are asleep.",     emoji: "👶" },
      { word: "berries",  sentence: "We picked sweet berries.",   emoji: "🫐" },
      { word: "cities",   sentence: "Australia has many big cities." },
      { word: "ladies",   sentence: "The ladies sat in the garden." },
      { word: "parties",  sentence: "Birthday parties are fun.",  emoji: "🎉" },
      { word: "stories",  sentence: "Grandpa tells the best stories.", emoji: "📖" },
      { word: "leaves",   sentence: "Leaves fall in autumn.",     emoji: "🍂" },
      { word: "knives",   sentence: "Be careful with sharp knives.", emoji: "🔪" },
      { word: "halves",   sentence: "Cut the apple into halves.", emoji: "🍎" },
      { word: "wolves",   sentence: "Wolves howl at the moon.",   emoji: "🐺" },
      { word: "shelves",  sentence: "Books fill the shelves.",    emoji: "📚" },
      { word: "scarves",  sentence: "We wore scarves in the snow.", emoji: "🧣" },
      { word: "foxes",    sentence: "Two foxes ran across the road.", emoji: "🦊" },
      { word: "boxes",    sentence: "Pack your toys in boxes.",   emoji: "📦" },
      { word: "dishes",   sentence: "I helped wash the dishes.",  emoji: "🍽️" },
      { word: "glasses",  sentence: "He wears glasses to read.",  emoji: "👓" },
      { word: "churches", sentence: "Old churches have tall towers.", emoji: "⛪" },
      { word: "branches", sentence: "Birds rested on the branches.", emoji: "🌳" }
    ],
    "Australian spellings": [
      { word: "centre",    sentence: "Meet me at the shopping centre." },
      { word: "metre",     sentence: "The rope is one metre long." },
      { word: "litre",     sentence: "Pour a litre of milk into the jug." },
      { word: "fibre",     sentence: "Vegetables have lots of fibre.", emoji: "🥦" },
      { word: "theatre",   sentence: "We saw a play at the theatre.", emoji: "🎭" },
      { word: "colour",    sentence: "Pick your favourite colour.", emoji: "🎨" },
      { word: "favour",    sentence: "Could you do me a favour?" },
      { word: "flavour",   sentence: "Strawberry is my favourite flavour.", emoji: "🍓" },
      { word: "harbour",   sentence: "Boats rest in the harbour.", emoji: "⛵" },
      { word: "neighbour", sentence: "My neighbour has a cat.",   emoji: "🏘️" },
      { word: "behaviour", sentence: "Good behaviour is rewarded." },
      { word: "humour",    sentence: "She has a great sense of humour.", emoji: "😄" },
      { word: "honour",    sentence: "It's an honour to meet you." },
      { word: "labour",    sentence: "Building the wall was hard labour." },
      { word: "vapour",    sentence: "Steam is water vapour.",    emoji: "💨" },
      { word: "grey",      sentence: "The clouds turned grey.",   emoji: "☁️" },
      { word: "defence",   sentence: "Our defence kept them scoreless." },
      { word: "offence",   sentence: "I meant no offence.", homophone: true },
    ],
    "Word endings (-tion, -ous, soft c/g)": [
      { word: "attention", sentence: "Pay attention in class." },
      { word: "station",   sentence: "We waited at the station.", emoji: "🚉" },
      { word: "action",    sentence: "Quick action saved the day." },
      { word: "question",  sentence: "I have one more question." },
      { word: "addition",  sentence: "We did addition in maths.", emoji: "➕" },
      { word: "motion",    sentence: "The boat rocked in motion." },
      { word: "fraction",  sentence: "Half is a fraction." },
      { word: "division",  sentence: "We learned division in maths.", emoji: "➗" },
      { word: "decision",  sentence: "It was a tough decision." },
      { word: "mansion",   sentence: "A grand mansion stood on the hill.", emoji: "🏰" },
      { word: "famous",    sentence: "She is a famous singer.",   emoji: "🎤" },
      { word: "nervous",   sentence: "I felt nervous before the test.", emoji: "😰" },
      { word: "jealous",   sentence: "Don't be jealous of others." },
      { word: "fabulous",  sentence: "The cake was fabulous.",    emoji: "🎂" },
      { word: "generous",  sentence: "She is a generous friend." },
      { word: "gentle",    sentence: "Be gentle with the kitten.", emoji: "🐱" },
      { word: "giant",     sentence: "The giant lived on a mountain.", emoji: "👹" },
      { word: "magic",     sentence: "The magic show was amazing.", emoji: "✨" },
      { word: "village",   sentence: "A tiny village in the hills.", emoji: "🏘️" }
    ]
  },

  "Year 5": {
    "Greek & Latin roots": [
      { word: "telephone",  sentence: "Answer the telephone, please.", emoji: "📞" },
      { word: "telescope",  sentence: "Through the telescope we saw Mars.", emoji: "🔭" },
      { word: "photograph", sentence: "Take a photograph of the sunset.", emoji: "📷" },
      { word: "photocopy",  sentence: "I made a photocopy of my notes." },
      { word: "autograph",  sentence: "I got the player's autograph.", emoji: "✍️" },
      { word: "microscope", sentence: "Use the microscope to see tiny things.", emoji: "🔬" },
      { word: "transport",  sentence: "Buses are a kind of transport.", emoji: "🚌" },
      { word: "portable",   sentence: "A laptop is portable." },
      { word: "predict",    sentence: "Predict what will happen next." },
      { word: "biology",    sentence: "We studied frogs in biology.", emoji: "🐸" },
      { word: "geography",  sentence: "Geography is about countries and maps.", emoji: "🗺️" },
      { word: "paragraph",  sentence: "Start a new paragraph here." },
      { word: "dictionary", sentence: "Look it up in the dictionary.", emoji: "📖" },
      { word: "aquarium",   sentence: "We visited the aquarium.",  emoji: "🐠" },
      { word: "popular",    sentence: "That song is very popular.", emoji: "🎵" },
      { word: "kilometre",  sentence: "The walk is one kilometre long." },
      { word: "hexagon",    sentence: "A hexagon has six sides." },
      { word: "triangle",   sentence: "Draw a triangle on the page.", emoji: "🔺" }
    ],
    "Tricky letter patterns": [
      { word: "although",  sentence: "I went out, although it was raining." },
      { word: "though",    sentence: "It looked easy, though it wasn't.", homophone: true },
      { word: "through",   sentence: "We walked through the forest.", homophone: true  },
      { word: "thought",   sentence: "I thought you were home." },
      { word: "brought",   sentence: "She brought a gift for me." },
      { word: "enough",    sentence: "Have you had enough to eat?" },
      { word: "rough",     sentence: "The road was rough and bumpy." },
      { word: "tough",     sentence: "The meat was tough to chew." },
      { word: "taught",    sentence: "My nan taught me to knit.",  emoji: "🧶" },
      { word: "caught",    sentence: "He caught a huge fish.",     emoji: "🎣" },
      { word: "naughty",   sentence: "The naughty puppy chewed my shoe." },
      { word: "daughter",  sentence: "His daughter plays football.", emoji: "⚽" },
      { word: "character", sentence: "Each book has a hero character." },
      { word: "technique", sentence: "She uses a clever technique." },
      { word: "machine",   sentence: "The washing machine is broken.", emoji: "🧺" },
      { word: "chemist",   sentence: "Pick up the medicine from the chemist.", emoji: "💊" },
      { word: "chorus",    sentence: "Sing along to the chorus.",  emoji: "🎶" },
      { word: "mechanic",  sentence: "The mechanic fixed our car.", emoji: "🔧" },
      { word: "plough",    sentence: "The farmer used a plough.",  emoji: "🚜" }
    ],
    "Suffix patterns (-able, -ible, -ous)": [
      { word: "valuable",     sentence: "This necklace is very valuable.", emoji: "💎" },
      { word: "usable",       sentence: "The old kettle is still usable." },
      { word: "comfortable",  sentence: "This couch is so comfortable.", emoji: "🛋️" },
      { word: "sensible",     sentence: "Wear sensible shoes for hiking.", emoji: "🥾" },
      { word: "possible",     sentence: "Anything is possible if you try." },
      { word: "horrible",     sentence: "The smell was horrible." },
      { word: "dangerous",    sentence: "Crossing without looking is dangerous.", emoji: "⚠️" },
      { word: "courageous",   sentence: "It was a courageous rescue." },
      { word: "enormous",     sentence: "We saw an enormous whale.", emoji: "🐋" },
      { word: "government",   sentence: "The government made a new law.", emoji: "🏛️" },
      { word: "friendship",   sentence: "Our friendship is strong.", emoji: "🤝" },
      { word: "neighbourhood",sentence: "Kids play in our neighbourhood.", emoji: "🏘️" },
      { word: "freedom",      sentence: "Birds enjoy freedom in the sky.", emoji: "🕊️" },
      { word: "scientist",    sentence: "A scientist studies nature.", emoji: "🔬" },
      { word: "electrician",  sentence: "The electrician fixed the wires.", emoji: "💡" },
      { word: "musician",     sentence: "A musician practises every day.", emoji: "🎵" },
      { word: "magician",     sentence: "The magician pulled a rabbit from a hat.", emoji: "🎩" },
      { word: "politician",   sentence: "The politician made a speech." }
    ]
  },

  "Year 6": {
    "Greek & Latin roots": [
      { word: "audible",       sentence: "Her whisper was barely audible.", emoji: "👂" },
      { word: "visible",       sentence: "Stars become visible at night.", emoji: "⭐" },
      { word: "invisible",     sentence: "The wind is invisible but strong." },
      { word: "describe",      sentence: "Describe what you saw at the show." },
      { word: "structure",     sentence: "The bridge has a strong structure.", emoji: "🌉" },
      { word: "construction",  sentence: "The construction took many months.", emoji: "🏗️" },
      { word: "manuscript",    sentence: "She finished her manuscript today.", emoji: "📜" },
      { word: "spectator",     sentence: "Each spectator cheered loudly." },
      { word: "hydration",     sentence: "Drink water for good hydration.", emoji: "💧" },
      { word: "hydrogen",      sentence: "Water contains hydrogen and oxygen." },
      { word: "thermometer",   sentence: "Check the thermometer for the temperature.", emoji: "🌡️" },
      { word: "chronological", sentence: "Put the events in chronological order.", emoji: "⏳" },
      { word: "autobiography", sentence: "She wrote her autobiography.", emoji: "📖" },
      { word: "biography",     sentence: "A biography tells a person's life story." },
      { word: "geology",       sentence: "Geology is the study of rocks.", emoji: "🪨" },
      { word: "psychology",    sentence: "Psychology studies how we think." },
      { word: "democracy",     sentence: "Australia is a democracy.",   emoji: "🗳️" },
      { word: "philosophy",    sentence: "Philosophy asks big questions." }
    ],
    "Word endings (-ance, -ence, -cian)": [
      { word: "possession",  sentence: "She kept her grandma's possession safe." },
      { word: "discussion",  sentence: "We had a long discussion about it." },
      { word: "expression",  sentence: "Her expression showed surprise.", emoji: "😲" },
      { word: "ambulance",   sentence: "The ambulance arrived quickly.", emoji: "🚑" },
      { word: "assistance",  sentence: "He asked for assistance." },
      { word: "distance",    sentence: "The distance to the shop is short." },
      { word: "important",   sentence: "It's important to be honest." },
      { word: "different",   sentence: "Everyone is different and special." },
      { word: "independent", sentence: "She is independent and brave." },
      { word: "confidence",  sentence: "He spoke with great confidence." },
      { word: "intelligence",sentence: "Dolphins show high intelligence.", emoji: "🐬" },
      { word: "experience",  sentence: "Camping was a new experience.", emoji: "⛺" },
      { word: "audience",    sentence: "The audience clapped loudly.", emoji: "👏" },
      { word: "patience",    sentence: "Fishing takes patience.",     emoji: "🎣" },
      { word: "existence",   sentence: "We are grateful for our existence." },
      { word: "difference",  sentence: "Spot the difference in the picture." },
      { word: "evidence",    sentence: "The detective found new evidence.", emoji: "🔎" },
      { word: "silence",     sentence: "We sat in complete silence.",  emoji: "🤫" }
    ],
    "Australian spellings": [
      { word: "organise",       sentence: "Let's organise our notes." },
      { word: "recognise",      sentence: "Do you recognise this song?", emoji: "🎵" },
      { word: "realise",        sentence: "I didn't realise it was so late." },
      { word: "criticise",      sentence: "Try not to criticise without thinking." },
      { word: "apologise",      sentence: "I want to apologise for being late." },
      { word: "summarise",      sentence: "Summarise the chapter in two lines." },
      { word: "advertise",      sentence: "Shops advertise on TV.",    emoji: "📺" },
      { word: "travelled",      sentence: "We travelled across Australia.", emoji: "🚗" },
      { word: "cancelled",      sentence: "The picnic was cancelled due to rain." },
      { word: "modelled",       sentence: "She modelled the new uniform." },
      { word: "marvellous",     sentence: "What a marvellous painting!", emoji: "🎨" },
      { word: "woollen",        sentence: "I wore a warm woollen jumper.", emoji: "🧶" },
      { word: "jewellery",      sentence: "Mum keeps her jewellery in a box.", emoji: "💍" },
      { word: "counsellor",     sentence: "The counsellor listened carefully." },
      { word: "programme",      sentence: "Watch your favourite TV programme.", emoji: "📺" },
      { word: "manoeuvre",      sentence: "The pilot did a tricky manoeuvre.", emoji: "✈️" },
      { word: "favourite",      sentence: "Blue is my favourite colour." },
      { word: "believe",        sentence: "I believe in you." }
    ]
  }
};
